---
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: discovery-server
build:
  tagPolicy:
    customTemplate:
      template: '{{.version}}-{{.sha}}'
      components:
        - name: version
          envTemplate:
            template: '{{.EFFECTIVE_VERSION}}'
        - name: sha
          inputDigest: {}
  insecureRegistries:
    - registry.local.gardener.cloud:5001
  artifacts:
    - image: local-skaffold/discovery-server
      ko:
        dependencies:
          paths:
            - cmd/discovery-server
            - cmd/discovery-server/app
            - cmd/discovery-server/app/options
            - internal/dynamiccert
            - internal/handler
            - internal/handler/certificate
            - internal/handler/openidmeta
            - internal/handler/workloadidentity
            - internal/metrics
            - internal/reconciler/certificate
            - internal/reconciler/openidmeta
            - internal/store
            - internal/store/certificate
            - internal/store/openidmeta
            - internal/utils
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/discovery-server
      hooks:
        after:
          - command: ["sh", "hack/skaffold-discovery-server-image-patch.sh"]
manifests:
  kustomize:
    paths:
      - example/local/discovery-server
deploy:
  kubectl:
    hooks:
      after:
        - host:
            command:
              - hack/wait-discovery-server-deployment.sh
              - deploy
profiles: []
