---
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: discovery-server
build:
  artifacts:
    - image: local-skaffold/discovery-server
      ko:
        dependencies:
          paths:
            - cmd/discovery-server
            - cmd/discovery-server/app
            - cmd/discovery-server/app/options
            - internal/dynamiccert
            - internal/handler
            - internal/handler/certificate
            - internal/handler/openidmeta
            - internal/handler/workloadidentity
            - internal/metrics
            - internal/reconciler/certificate
            - internal/reconciler/openidmeta
            - internal/store
            - internal/store/certificate
            - internal/store/openidmeta
            - internal/utils
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/discovery-server
deploy:
  helm:
    hooks:
      before:
        - host:
            command:
              - ./hack/create-tls-secret.sh
    releases:
      - name: gardener-discovery-server
        chartPath: charts/discovery-server
        valuesFiles:
          - example/local/values.yaml
        namespace: garden
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_local_skaffold_discovery_server}}'
          image.tag: '{{.IMAGE_TAG_local_skaffold_discovery_server}}@{{.IMAGE_DIGEST_local_skaffold_discovery_server}}'
        createNamespace: true
        wait: false
profiles: []
